# Change these first
owner: ventanarj # Your GitHub organization or username, where this repository lives
repo: status-nutrium # The name of this repository

sites:
  - name: App Nutrium
    url: https://app.nutrium.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-nutrium
  name: Status Nutrium Monitor
  introTitle: "**Status Nutrium Monitor**"
  introMessage: Esta página apresenta o monitoramento de disponibilidade do site Nutrium.com, com atualização automática via GitHub Actions.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
